---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: exampleSite/content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/search
  label: Search
  create: all
  match: "**/*"
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.50'
